### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
import numpy as np

original_array = np.array([[3., 2., np.nan, 1.],
                           [10., 12., 10., 9.],
                           [5., np.nan, 1., np.nan]])

In [2]:
missing_data = np.isnan(original_array)

In [3]:
# Print missing data
print("\n Missing data of the said array:")
print(missing_data)


 Missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [4]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array3 = np.array([[1, 2, 3], [4, 5, 7]])

# Check if array1 and array2 are equal
result_equal_1_2 = np.array_equal(array1, array2)

# Check if array1 and array3 are equal
result_equal_1_3 = np.array_equal(array1, array3)

# Print results
print("\nAre array1 and array2 equal?")
print(result_equal_1_2)

print("Are array1 and array3 equal?")
print(result_equal_1_3)


Are array1 and array2 equal?
True
Are array1 and array3 equal?
False


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [5]:
# Create a 4x4 array with random values
original_array = np.random.randint(0, 16, (4, 4))

# Create a new array by swapping the first and last rows
new_array = original_array.copy()
new_array[[0, -1], :] = new_array[[-1, 0], :]

# Print the new array
print("\nNew array after swapping first and last rows of the said array:")
print(new_array)


New array after swapping first and last rows of the said array:
[[14  4  9 11]
 [ 4  9 13 15]
 [12 14  7  9]
 [13 15 12  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [6]:
# Convert a list to an array
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)

# Convert a tuple to an array
tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)

# Print the original list and tuple
print("Original list:")
print(list_data)

print("\nOriginal tuple:")
print(tuple_data)

# Print the arrays
print("\nArray from list:")
print(array_from_list)

print("\nArray from tuple:")
print(array_from_tuple)

Original list:
[1, 2, 3, 4, 5]

Original tuple:
(6, 7, 8, 9, 10)

Array from list:
[1 2 3 4 5]

Array from tuple:
[ 6  7  8  9 10]


###### 5. Write a NumPy program to find common values between two arrays.

In [7]:
# Sample arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between array1 and array2
common_values = np.intersect1d(array1, array2)

# Print the original arrays
print("Array 1:", array1)
print("Array 2:", array2)

# Print common values
print("\nCommon values between Array 1 and Array 2:")
print(common_values)

Array 1: [1 2 3 4 5]
Array 2: [3 4 5 6 7]

Common values between Array 1 and Array 2:
[3 4 5]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [8]:
# Original array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])

# Reshape the array to 3x2
reshaped_array_3x2 = np.reshape(original_array, (3, 2))

# Reshape the array to 2x3
reshaped_array_2x3 = np.reshape(original_array, (2, 3))

# Print the reshaped arrays
print("\nReshape 3x2:")
print(reshaped_array_3x2)

print("\nReshape 2x3:")
print(reshaped_array_2x3)


Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]

Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [9]:
# Original array
original_array = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

# Find unique values and their counts
unique_values, counts = np.unique(original_array, return_counts=True)

# Create a frequency array
frequency_array = np.array([unique_values, counts])

# Print the frequency of unique values
print("\nFrequency of unique values of the said array:")
print(frequency_array)


Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [10]:
# Original arrays
array1 = np.array([[0, 0, 0], [1, 2, 3], [4, 5, 6]])
array2 = np.array([10, 11, 12])

# Perform broadcasting to add the arrays
result_array = array1 + array2

# Print the new array after broadcasting
print("\nNew Array:")
print(result_array)


New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [11]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))

print("\nExtracted data: Second row")
print(arra_data[1,:])


Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [12]:
# Original array
original_array = np.array([[0, 1, 2, 3],
                           [4, 5, 6, 7],
                           [8, 9, 10, 11],
                           [12, 13, 14, 15]])

# Extract third and fourth elements of the first and second rows
extracted_data = original_array[:2, 2:4]

# Print the extracted data
print("\nExtracted data: Third and fourth elements of the first and second rows")
print(extracted_data)


Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [13]:
import datetime

# Get today's date
today = np.datetime64('today', 'D')

# Get yesterday's date
yesterday = today - np.timedelta64(1, 'D')

# Get tomorrow's date
tomorrow = today + np.timedelta64(1, 'D')

# Convert to standard datetime objects for better readability
today_dt = np.datetime_as_string(today, unit='D')
yesterday_dt = np.datetime_as_string(yesterday, unit='D')
tomorrow_dt = np.datetime_as_string(tomorrow, unit='D')

# Print the results
print("Yesterday:", yesterday_dt)
print("Today:", today_dt)
print("Tomorrow:", tomorrow_dt)

Yesterday: 2024-01-28
Today: 2024-01-29
Tomorrow: 2024-01-30


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [14]:
# Define the target month and year
target_month = 5  # May
target_year = 2017

# Create the starting date for the target month
start_date = np.datetime64(f'{target_year}-{target_month:02d}-01')

# Calculate the day of the week for the first day of the month (0 is Monday)
day_of_week = np.datetime64(start_date, 'D').view('int64') % 7

# Calculate the number of days to the first Monday
days_to_monday = (7 - day_of_week) % 7

# Calculate the first Monday in the target month
first_monday = start_date + np.timedelta64(days_to_monday, 'D')

# Print the result
print("First Monday in May 2017:")
print(first_monday)

First Monday in May 2017:
2017-05-04
