### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [2]:
array_zeros = np.zeros(10)
array_ones = np.ones(10)
array_fives = np.full(10, 5)

print("An array of 10 zeros:")
print(array_zeros)

print("\nAn array of 10 ones:")
print(array_ones)

print("\nAn array of 10 fives:")
print(array_fives)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [3]:
integer_array = np.arange(30, 71)

print("Array of the integers from 30 to 70:")
print(integer_array)

Array of the integers from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [4]:
even_integer_array = np.arange(10, 51, 2)

print("Array of all the even integers from 10 to 50:")
print(even_integer_array)

Array of all the even integers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [5]:
identity_matrix = np.identity(3)

print("3x3 matrix:")
print(identity_matrix)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [6]:
random_number = np.random.random()

print("Random number between 0 and 1:")
print(random_number)

Random number between 0 and 1:
0.5911696180075469


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [7]:
random_numbers = np.random.randn(15)

print("15 random numbers from a standard normal distribution:")
print(random_numbers)

15 random numbers from a standard normal distribution:
[-0.67660889 -0.06792325  0.99635659  0.36408363 -0.69990578 -2.02870594
  1.30124602  0.4939867   1.48590717 -0.24911054  1.11512077  1.43151651
  2.97119639  0.93568722 -0.34133789]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [8]:
original_array = np.array([[10, 11, 12, 13],
                           [14, 15, 16, 17],
                           [18, 19, 20, 21]])
print("Original array:")
print(original_array)

print("Each element of the array is:")
for row in original_array:
    for element in row:
        print(element, end=" ")
print()

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 


###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [9]:
vector_1 = np.array([1, 8, 3, 5])
vector_2 = np.array([10, 1, 4, 10])

result_vector = np.multiply(vector_1, vector_2)

print("Vector-1")
print(vector_1)

print("Vector-2")
print(vector_2)

print("Multiply the values of two said vectors:")
print(result_vector)

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [10]:
original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

print("Original array:")
print(original_array)

reverse_array = np.flip(original_array)
print("Reverse array:")
print(reverse_array)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [11]:
zero_matrix = np.zeros((5, 5), dtype=int)

np.fill_diagonal(zero_matrix, [1, 2, 3, 4, 5])

print(zero_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [12]:
original_array = np.array([[0, 1],
                           [2, 3]])
print("Original array:")
print(original_array)

sum_all_elements = np.sum(original_array)

sum_each_column = np.sum(original_array, axis=0)

sum_each_row = np.sum(original_array, axis=1)

print("Sum of all elements:")
print(sum_all_elements)

print("Sum of each column:")
print(sum_each_column)

print("Sum of each row:")
print(sum_each_row)

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [13]:
vector_1 = np.array([4, 5])
vector_2 = np.array([7, 10])

print("Original vectors:")
print(vector_1)
print(vector_2)

inner_product = np.dot(vector_1, vector_2)

print("Inner product of said vectors:")
print(inner_product)

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
